spring:
  datasource:
    password: minhngoc123
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hotelmanagement

server:
  path-file-update: src\main\resources\static\images